version: '3'
services:
  cli:
    image: webdevops/php-dev:8.3
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    env_file: .env
    depends_on:
      - db

  db:
    image: mysql:9.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/db/dumps/:/dumps/
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"

volumes:
    mysql_data:
